let heading = document.createElement("h1");
heading.innerText="";
heading.className="heading";
document.body.append(heading);
setTimeout(()=>{
    heading.innerText="10";
    setTimeout(()=>{
        heading.innerText="9";
        setTimeout(()=>{
            heading.innerText="8";
            setTimeout(()=>{
                heading.innerText="7";
                setTimeout(()=>{
                    heading.innerText="6";
                    setTimeout(()=>{
                        heading.innerText="5";
                        setTimeout(()=>{
                            heading.innerText="4";
                            setTimeout(()=>{
                                heading.innerText="3";
                                setTimeout(()=>{
                                    heading.innerText="2";
                                    setTimeout(()=>{
                                        heading.innerText="1";
                                        setTimeout(()=>{
                                            heading.innerText="0";
                                            setTimeout(()=>{
                                                heading.innerText="HAPPY INDEPENDENCE DAY !!!!";
                                            },1000)
                                        },1000)
                                    },1000)
                                },1000)
                            },1000)
                        },1000)
                    },1000)
                },1000)
            },1000)
        },1000)
    },1000)
},1000)